title: "김로그의 우당탕탕"
url: "https://kimlog.pages.dev"
lang: ko
description: "KIMLOG―Need, Learn and Build"
logo: /assets/images/profile.png
future: true
exclude:
  - "**/draft-*.md"
theme: minima
plugins:
  - jekyll-feed
  - jekyll-redirect-from
  - jekyll-sitemap
collections:
  content:
    output: true
    permalink: /:path/
  reviews:
    output: false
header_pages:
  - devlog.html
  - ue5.html
  - audio.html
  - apps.html
  - til.html
  - contact.html
