title: "김로그의 우당탕탕"
description: "KIMLOG―Need, Learn and Build"
logo: /assets/images/profile.png
theme: minima
plugins:
  - jekyll-feed
  - jekyll-redirect-from
collections:
  devlog:
    output: true
    permalink: /devlog/:path/
header_pages:
  - devlog.html
  - android-studio.html
  - ue5.html
  - apps.html
  - til.html
  - contact.html
